### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by Sliicy** [rootCBR/DisruptManager#11]
Hi there, I'd like to know where the source code is so that we can contribute to the project.
Thank you,

**Comment by AddioElectronics** [comment]
Its written in C# so you can use [ILSpy](https://github.com/icsharpcode/ILSpy) to view it.

**Comment by rootCBR** [comment]
What would you like to contribute to?

**Comment by Sliicy** [comment]
@rootCBR  I just feel more comfortable running it if its open source. Also, hosting it on GitHub and not open sourcing it kinda defeats putting it on GitHub in my humble opinion, unless of course you want git versioning for private use.
Also, if one day Ubisoft changes the way the game works and this breaks functionality in your tool, at least others can fork a version and improve it if you ever decide to abandon the project.

Thank you anyways for your hard work!
