### ISSUE TITLE
put actual directions on the fucking download page

### ISSUE THREAD

**Issue by ghost** [rootCBR/DisruptManager#12]
the fact that I had to look up a youtube video just to figure out where to put the mods is fucking abysmal. This is a good tool, but holy shit. Don't just label the folders by game with nothing showing any information inside. At least put even a blank text file saying "PUT MODS HERE" would be fucking passable. I only created this account to give you shit for that very piece.

**Comment by rootCBR** [comment]
Three games, three profiles, three folders, but my bad for not anticipating the challenge this might present to some
