### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by Krynzm** [rootCBR/DisruptManager#2]
I followed all the instructions given carefully, and when I try to install a mod it crashes, or if it doesn't, then the mods don't work at all

**Comment by NihlusCreed** [comment]
same thing is happening to me... i see this dude commented his issue on mar 27 with no reply so im guessing ill get the same treatment ?

**Comment by rootCBR** [comment]
I'll keep this issue in mind when I next continue to work on Disrupt Manager. Though I'll need more information than this.
What mods are you trying to install? When exactly does it crash? Can it be reproduced? How do you know the mods aren't working at all?

**Comment by Caliber9** [comment]
hello im having this problem as well here is exactly what i did
1. made a new folder on my pc (not within the watch dogs legion folder which may be the problem?)
2. downloaded the manager
3. downloaded a few mods off of nexus for watch dogs legion (prestige operatives, extra clothes, WDL inventory and operative editor)
4. ran the manager
5. gave it the directory to my game (in this case steam)
6. clicked the check box on a mod
7. crash
repeat
i tried deleting the files and re extracting them to try again but no luck
any ideas?

also sometimes the manager will crash after i hit OK once i select my directory

EDIT: big(?) news: i decided to try uninstalling some mods and found that when the mod "WDL inventory and operative editor" was removed that the mod manager did not crash
for anyone experiencing this issue try removing the aforementioned mod and see if the issue resolves itself
also make sure Ubisoft Connect is set to offline if required so your mods work properly
lastly dont do what i did and forget to install the mods: select the mods you want, click "Game" at the top, click "Install Mods" or "Install Mods And Play"

apologies for the long comment thank you for your time

**Comment by rootCBR** [comment]
How did you install the inventory and operative editor mod? If you've put that zip archive next to the others, it would explain why it crashed. Many mods come as zip archives, but many of them are not made to be compatible with Disrupt Manager.
That said, I may be able to improve how the program handles incompatible archives.

**Comment by Caliber9** [comment]
i went to nexus mods and did a manual download
added it to the manager like the others and when i launched it the name did not show up for the mod and no description was available
ill attach a screen shot of the error
![Desktop Screenshot 2023 06 11 - 16 24 12 38 (2)](https://github.com/rootCBR/DisruptManager/assets/90571706/dd5890c2-63d7-4866-b8f5-6e0f30d2b699)
![Desktop Screenshot 2023 06 11 - 16 26 03 85 (2)](https://github.com/rootCBR/DisruptManager/assets/90571706/2ba94fa5-fa89-42ab-9386-609a912b9d79)

i already deleted the mod but it looked the exact same as those in the second picture
and the first picture was from before i found the error
if you want me to redownload the mod and get better screen shots let me know

**Comment by rootCBR** [comment]
So what I said earlier applies. You'll need to make sure the mods you want to use are made to work with Disrupt Manager.
