### ISSUE TITLE
Exception Error when trying to setup DisruptManager

### ISSUE THREAD

**Issue by mayday24** [rootCBR/DisruptManager#22]
I am trying to mod Watch Dogs Legion and when I try to run DisruptManager.exe I receive an error immediately. I have no clue how to fix this and cannot find anything on google either. Any help would be greatly appreciated. Thanks.

![DisruptManager_error](https://github.com/user-attachments/assets/3e539708-a571-421a-8c3a-0871ae35a661)

**Comment by rootCBR** [comment]
Fixed in the latest release 1.1.9056.37402
