### ISSUE TITLE
it doesnt work at all it doesnt even open

### ISSUE THREAD

**Issue by Avgud11** [rootCBR/DisruptManager#3]
when you download it and extract the files, nothing even opens. they need to fix this asap

**Comment by Avgud11** [comment]
does anyone know how to install this? i install it, double click the .exe and nothing comes up or loads. why do they make everything so complicated and why dont they just put instructions some where

**Comment by rootCBR** [comment]
Instructions are not necessary, the installation process simply consists of extracting the archive content to the local file system. If that's what you've done and running DisruptManager.exe doesn't do anything, I'm gonna need more information.

See if running the program on another drive changes anything. Furthermore, after running the program, there should be a debug.log file in its directory. Sharing that with me could give me some hints as to what's happening.

**Comment by Avgud11** [comment]
> 

so i download the file, i open it and double click the disruptmanager and then it asks me to extract the files which i do. they are extracted on my desktop but when i double click the new .exe nothing happens. also i cant see any debug log files

**Comment by Avgud11** [comment]
i dont have another divice to test it on either but my system should be able to use it

**Comment by Federation60** [comment]
@rootCBR can you please tell me how to fix this

**Comment by Federation60** [comment]
@rootCBR

**Comment by Avgud11** [comment]
@rootCBR can you respond so that i can use mods in the game thanks

**Comment by Avgud11** [comment]
@rootCBR can you please respond? im trying to mod the game but the .exe wont work

**Comment by rootCBR** [comment]
Try extracting the archive contents before starting the application, or do the same with a different release version. Also make sure you have the [.NET Framework 4.81 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer) installed.

**Comment by Avgud11** [comment]
> 

thanks for replying, i installed the network framework 4.81 but the app still doesnt open. im going to send a video of what happens so you can see

**Comment by Avgud11** [comment]
https://github.com/rootCBR/DisruptManager/assets/137520766/3749d8ef-e10c-4234-b442-15e7e3db4129

**Comment by Avgud11** [comment]
> Try extracting the archive contents before starting the application, or do the same with a different release version. Also make sure you have the [.NET Framework 4.81 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer) installed.

i also tried to open the app with the older version but the same thing happened

**Comment by rootCBR** [comment]
I've never tested compatibility with Windows 11, that may or may not be the cause.

**Comment by Avgud11** [comment]
> I've never tested compatibility with Windows 11, that may or may not be the cause.

i may have fixed the issue, using campatability trouble shooter i ran the program in windows 8 and it seems to open now, ill see if this version causes any errors down the line

**Comment by Avgud11** [comment]
i dont know if it works or not, i put mods into the mods folder i made in the extracted file but none show up when running the app, i selected the correct mod folder location as well

> I've never tested compatibility with Windows 11, that may or may not be the cause.

**Comment by Avgud11** [comment]
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/42cb604b-e8d9-4ae9-920f-6031a0648e8e)
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/8f692268-eefc-4884-a7c0-367fbb9aaccd)

**Comment by Avgud11** [comment]
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/457a42ad-15a6-4cb0-a322-8ae98999acab)

**Comment by Avgud11** [comment]
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/62dec6de-f037-4b84-a432-b3eff1d23b2d)

**Comment by rootCBR** [comment]
You need to select your game directory, in this case Watch Dogs Legion's. Then put your mod archives into the corresponding folder that is next to DisruptManager.exe.

**Comment by Avgud11** [comment]
so i changed the location of the game directory to C:/Program Files (x86)/Ubisoft/Ubisoft Game Launcher/games/Watch Dogs Legion/. do i keep the mods folder where it is because it was already in the same folder as the distruptmanager.exe 
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/36c73093-8bb9-405c-a76c-202f3b403faa)


> You need to select your game directory, in this case Watch Dogs Legion's. Then put your mod archives into the corresponding folder that is next to DisruptManager.exe.

**Comment by rootCBR** [comment]
You put the mods into one of the existing folders for your game as seen above (Watch Dogs Legion). You don't create your own folder.

**Comment by Federation60** [comment]
> You put the mods into one of the existing folders for your game as seen above (Watch Dogs Legion). You don't create your own folder.

ok, i deleted the mods folder and put the mods into the watch dogs legion existing file but the mods still dont show up 
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/4401b0d2-e1f2-473e-a32c-5772270b4008)
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/13ffe86a-27c6-451e-b320-df97a34f14d2)

**Comment by Avgud11** [comment]
ok so i deleted the mods folder and moved the mod into the watch dogs legion folder already exisiting but the mods still dont show up 
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/7b190f8e-ab09-4734-82ee-a2e42ed4d287)
![image](https://github.com/rootCBR/DisruptManager/assets/137520766/7595a0c2-ecdc-488a-bfde-973dd151ad28) 
@rootCBR

**Comment by Avgud11** [comment]
> You put the mods into one of the existing folders for your game as seen above (Watch Dogs Legion). You don't create your own folder.

there is still an issue, do you know why? none of the mods show up even though i put them in the watch dogs legion folder and and selected them in the menu

**Comment by Avgud11** [comment]
Can you help with this one last bit please @rootCBR
