### ISSUE TITLE
Any ideas on how to run the software on old windows 10s unsupported .net framework runtime  4.8.1

### ISSUE THREAD

**Issue by GHOSTagw** [rootCBR/DisruptManager#7]
![图片](https://github.com/rootCBR/DisruptManager/assets/40930046/2e80b2b2-e0e6-4591-ba82-44b6b7025d09)

Windows 10 LTSC 2019 version 1809

**Comment by rootCBR** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net481-web-installer
